environment:
#  nodejs_version: "0.12.7"
  matrix:
    # First group is 32 bit python 2.7
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "32"
  # Add custom environmental variables for pip
  PIP: C:\\Python34\Scripts\pip
  # Add custom environmental variables to ensure 32 bit electron
#  npm_config_arch: ia32

platform: x86

configuration: Release

init:
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
#  - cmd: wmic OS get OSArchitecture

  # As AppVeyor has multiple python install, verify which ones will be used
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: "%PYTHON%\\python --version"
  - cmd: "%PYTHON%\\python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Prepare pip and pip3, PATH iterated left to right first hit wins
  - cmd: set PATH=%PYTHON%\scripts;%PATH
  - cmd: ECHO Path - %PATH%

  # Ensure node x86 (appveyor powershell script to switch installed versions)
#  - ps: Install-Product node 5.1.0 x86
#  - cmd: node --version
#  - cmd: npm --version

install:
  # Git clone happens between init and install
  - cmd: git submodule update --init --recursive

  # Install Python packages
  - cmd: "%PIP% install https://dl.dropboxusercontent.com/u/74034/ardublockly-dep/win/py2exe-0.9.2.2-cp34-none-win32.whl"
  - cmd: "%PIP% install mkdocs"
  - cmd: "%PIP% freeze"

  # Build and pack Otone App - based off of Ardublockly
  - cmd: "%PYTHON%\\python package\\build_py2exe.py"
#  - cmd: cd package\electron && npm install && cd ..\..\
#  - cmd: cd package\electron && npm run release && cd ..\..\
#  - cmd: "%PYTHON3%\\python package\\pack_ardublockly.py"
#  - cmd: dir

# Not a project with an msbuild file, build done at install.
build: off
