environment:
  nodejs_version: "4.4.7"
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "32"
  npm_config_arch: ia32
platform: x86

configuration: Release

init:
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture
  - cmd: npm config set msvs_version 2015 --global
  # As AppVeyor has multiple python install, verify which one uses by default
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"

  # Set the relevant python and pip location to the path
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

  # Verify the new default python
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: pip --version

  # Check out installed python packages
  - cmd: pip freeze

install:
  - cmd: git submodule update --init --recursive
  - cmd: pip install https://dl.dropboxusercontent.com/s/ks2ye06y1azkit8/py2exe-0.9.2.2-cp34-none-win32.whl
#  - cmd: pip install mkdocs
  - cmd: pip freeze
  - cmd: python scripts\build_py2exe.py

  - cmd: cp otexec\backexec\otone_client.exe backend-dist\win\
  - cmd: node --version
  - cmd: npm --version
  - cmd: npm install electron-packager --save-dev
  - cmd: npm install electron-packager -g
  - cmd: set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\npm\node_modules\electron-packager
  - cmd: cd C:\Users\appveyor\AppData\Roaming\npm\node_modules\electron-packager
  - cmd: dir
  - cmd: cd C:\projects\otone-frontend
  - cmd: python scripts\build_electron_app_win.py
