os: Visual Studio 2015

environment:
  nodejs_version: "6.0.0"
  matrix:
    - language: cpp
      PYTHON3: "C:\\Python34"
      PYTHON3_VERSION: "3.4.3"
      PYTHON3_ARCH: "32"

      # PYTHON2.7 REQUIRED FOR NODE-GYP & ELECTRON
      PYTHON2: "C:\\Python27"
      PYTHON2_VERSION: "2.7.9"
      PYTHON2_ARCH: "32"

  PIP3: C:\\Python34\Scripts\pip
  PIP2: C:\\Python27\Scripts\pip

  npm_config_arch: ia32



platform: x86

configuration: Release

init:
  - cmd: node --version
  - cmd: npm --version

  - "ECHO Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture
  - cmd: npm config set msvs_version 2015 --global

  - cmd: ECHO %PYTHON3% %PYTHON3_VERSION% %PYTHON3_ARCH%
  - cmd: "%PYTHON3%\\python --version"
  - cmd: "%PYTHON3%\\python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - cmd: "%PYTHON3%\\python -m pip install --upgrade pip"

  - cmd: ECHO %PYTHON2% %PYTHON2_VERSION% %PYTHON2_ARCH%
  - cmd: "%PYTHON2%\\python --version"
  - cmd: "%PYTHON2%\\python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - cmd: "%PYTHON2%\\python -m pip install --upgrade pip"

  - ps: Install-Product node 6.0.0 x86
  - cmd: node --version
  - cmd: npm --version

  # SET THE RELEVANT PYTHON AND PIP LOCATIONS IN THE PATH
  - cmd: set PATH=%PYTHON3%;%PYTHON3%\scripts;%PYTHON2%;%PYTHON2%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

install:
  # NOTE: OTONE-FRONTEND NOW CLONED INTO C:\\PROJECTS\OTOONE-FRONTEND

  # 1. INSTALL PYTHON DEPENDENCIES
  - cmd: "%PIP3% install -r requirements.txt"

  - cmd: "%PIP2% freeze"
  - cmd: "%PIP3% freeze"

# 3. PREPARE NPM FOR ELECTRON APP BUILD
  - cmd: npm config list
  - cmd: npm config set python %PYTHON2%\python.exe --global
  - cmd: npm install node-gyp
  - cmd: npm install node-gyp -g
#  - cmd: node-gyp --python %PYTHON2%
#  - cmd: npm install bufferutil -g
#  - cmd: npm install electron-packager --save-dev
#  - cmd: npm install electron-packager -g
#  - cmd: npm install electron-prebuilt --save-dev
#  - cmd: npm install electron-prebuilt -g
#  - cmd: npm prune

  # INSTALL NODE DEPENDENCIES
  # - cmd: set PATH=%PATH%;C:\projects\appveyor\node_modules\
  # - cmd: cd C:\projects\otone-frontend
  - cmd: npm install && cd app && npm install && cd ..
  - npm run release:win

  # 5. BUILD ELECTRON APP
  # - cmd: "%PYTHON3%\\python scripts\\build_electron_app.py"

# 6. PACKAGE ELECTRON APP
  - cmd: dir
  # RELEASES DIRECTORY REQUIRED FOR scripts\zip_ot_app.py

  - cmd: dir app
  - cmd: dir backend\backend
  - cmd: dir out
  - cmd: dir build

  - cmd: dir releases
  - cmd: dir out\OpenTrons-win32-ia32


build: off

before_deploy:
  - ps: Get-ChildItem .\releases\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName OTAppWin}

deploy:
  - provider: S3
    access_key_id: $(AWS_ACCESS_KEY)
    secret_access_key: $(AWS_SECRET_KEY)
    bucket: ot-app-builds
    region: us-east-1
    set_public: true
    folder: win
    artifact: OTAppWin
    on:
      branch: 16-add-ci-cd-pipeline-for-windows-app-frontend
